/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_beatmap_free(a: number, b: number): void;
export function __wbg_beatmapattributes_free(a: number, b: number): void;
export function __wbg_beatmapattributesbuilder_free(a: number, b: number): void;
export function __wbg_difficulty_free(a: number, b: number): void;
export function __wbg_difficultyattributes_free(a: number, b: number): void;
export function __wbg_get_beatmapattributes_ar(a: number): number;
export function __wbg_get_beatmapattributes_arHitWindow(a: number, b: number): void;
export function __wbg_get_beatmapattributes_baseAr(a: number): number;
export function __wbg_get_beatmapattributes_baseOd(a: number): number;
export function __wbg_get_beatmapattributes_clockRate(a: number): number;
export function __wbg_get_beatmapattributes_cs(a: number): number;
export function __wbg_get_beatmapattributes_hp(a: number): number;
export function __wbg_get_beatmapattributes_od(a: number): number;
export function __wbg_get_beatmapattributes_odGoodHitWindow(a: number, b: number): void;
export function __wbg_get_beatmapattributes_odGreatHitWindow(a: number, b: number): void;
export function __wbg_get_beatmapattributes_odMehHitWindow(a: number, b: number): void;
export function __wbg_get_beatmapattributes_odOkHitWindow(a: number, b: number): void;
export function __wbg_get_beatmapattributes_odPerfectHitWindow(a: number, b: number): void;
export function __wbg_get_difficultyattributes_aimDifficultStrainCount(a: number, b: number): void;
export function __wbg_get_difficultyattributes_ar(a: number, b: number): void;
export function __wbg_get_difficultyattributes_color(a: number, b: number): void;
export function __wbg_get_difficultyattributes_consistencyFactor(a: number, b: number): void;
export function __wbg_get_difficultyattributes_greatHitWindow(a: number, b: number): void;
export function __wbg_get_difficultyattributes_hp(a: number, b: number): void;
export function __wbg_get_difficultyattributes_isConvert(a: number): number;
export function __wbg_get_difficultyattributes_legacyScoreBaseMultiplier(a: number, b: number): void;
export function __wbg_get_difficultyattributes_maxCombo(a: number): number;
export function __wbg_get_difficultyattributes_maximumLegacyComboScore(a: number, b: number): void;
export function __wbg_get_difficultyattributes_mechanicalDifficulty(a: number, b: number): void;
export function __wbg_get_difficultyattributes_mehHitWindow(a: number, b: number): void;
export function __wbg_get_difficultyattributes_mode(a: number): number;
export function __wbg_get_difficultyattributes_monoStaminaFactor(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nCircles(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nDroplets(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nFruits(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nHoldNotes(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nLargeTicks(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nObjects(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nSliders(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nSpinners(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nTinyDroplets(a: number, b: number): void;
export function __wbg_get_difficultyattributes_nestedScorePerObject(a: number, b: number): void;
export function __wbg_get_difficultyattributes_okHitWindow(a: number, b: number): void;
export function __wbg_get_difficultyattributes_preempt(a: number, b: number): void;
export function __wbg_get_difficultyattributes_reading(a: number, b: number): void;
export function __wbg_get_difficultyattributes_readingDifficultNoteCount(a: number, b: number): void;
export function __wbg_get_difficultyattributes_rhythm(a: number, b: number): void;
export function __wbg_get_difficultyattributes_speedDifficultStrainCount(a: number, b: number): void;
export function __wbg_get_difficultyattributes_speedNoteCount(a: number, b: number): void;
export function __wbg_get_difficultyattributes_speedTopWeightedSliderFactor(a: number, b: number): void;
export function __wbg_get_difficultyattributes_stamina(a: number, b: number): void;
export function __wbg_get_difficultyattributes_stars(a: number): number;
export function __wbg_get_performanceattributes_aimEstimatedSliderBreaks(a: number, b: number): void;
export function __wbg_get_performanceattributes_comboBasedEstimatedMissCount(a: number, b: number): void;
export function __wbg_get_performanceattributes_difficulty(a: number): number;
export function __wbg_get_performanceattributes_effectiveMissCount(a: number, b: number): void;
export function __wbg_get_performanceattributes_estimatedUnstableRate(a: number, b: number): void;
export function __wbg_get_performanceattributes_pp(a: number): number;
export function __wbg_get_performanceattributes_ppAccuracy(a: number, b: number): void;
export function __wbg_get_performanceattributes_ppAim(a: number, b: number): void;
export function __wbg_get_performanceattributes_ppDifficulty(a: number, b: number): void;
export function __wbg_get_performanceattributes_ppFlashlight(a: number, b: number): void;
export function __wbg_get_performanceattributes_ppReading(a: number, b: number): void;
export function __wbg_get_performanceattributes_ppSpeed(a: number, b: number): void;
export function __wbg_get_performanceattributes_scoreBasedEstimatedMissCount(a: number, b: number): void;
export function __wbg_get_performanceattributes_speedDeviation(a: number, b: number): void;
export function __wbg_get_performanceattributes_speedEstimatedSliderBreaks(a: number, b: number): void;
export function __wbg_get_performanceattributes_state(a: number): number;
export function __wbg_get_strains_aim(a: number, b: number): void;
export function __wbg_get_strains_aimNoSliders(a: number, b: number): void;
export function __wbg_get_strains_color(a: number, b: number): void;
export function __wbg_get_strains_flashlight(a: number, b: number): void;
export function __wbg_get_strains_mode(a: number): number;
export function __wbg_get_strains_movement(a: number, b: number): void;
export function __wbg_get_strains_reading(a: number, b: number): void;
export function __wbg_get_strains_rhythm(a: number, b: number): void;
export function __wbg_get_strains_sectionLength(a: number): number;
export function __wbg_get_strains_singleColorStamina(a: number, b: number): void;
export function __wbg_get_strains_speed(a: number, b: number): void;
export function __wbg_get_strains_stamina(a: number, b: number): void;
export function __wbg_get_strains_strains(a: number, b: number): void;
export function __wbg_gradualdifficulty_free(a: number, b: number): void;
export function __wbg_gradualperformance_free(a: number, b: number): void;
export function __wbg_performance_free(a: number, b: number): void;
export function __wbg_performanceattributes_free(a: number, b: number): void;
export function __wbg_strains_free(a: number, b: number): void;
export function beatmap_ar(a: number): number;
export function beatmap_bpm(a: number): number;
export function beatmap_convert(a: number, b: number, c: number, d: number): void;
export function beatmap_cs(a: number): number;
export function beatmap_hitObjectTimes(a: number, b: number): void;
export function beatmap_hp(a: number): number;
export function beatmap_isConvert(a: number): number;
export function beatmap_isSuspicious(a: number): number;
export function beatmap_mode(a: number): number;
export function beatmap_nBreaks(a: number): number;
export function beatmap_nCircles(a: number): number;
export function beatmap_nHolds(a: number): number;
export function beatmap_nObjects(a: number): number;
export function beatmap_nSliders(a: number): number;
export function beatmap_nSpinners(a: number): number;
export function beatmap_new(a: number, b: number): void;
export function beatmap_od(a: number): number;
export function beatmap_sliderMultiplier(a: number): number;
export function beatmap_sliderTickRate(a: number): number;
export function beatmap_stackLeniency(a: number): number;
export function beatmap_version(a: number): number;
export function beatmapattributesbuilder_build(a: number): number;
export function beatmapattributesbuilder_new(a: number, b: number): void;
export function beatmapattributesbuilder_set_ar(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_clock_rate(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_cs(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_fixed_ar(a: number, b: number): void;
export function beatmapattributesbuilder_set_fixed_cs(a: number, b: number): void;
export function beatmapattributesbuilder_set_fixed_hp(a: number, b: number): void;
export function beatmapattributesbuilder_set_fixed_od(a: number, b: number): void;
export function beatmapattributesbuilder_set_hp(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_is_convert(a: number, b: number): void;
export function beatmapattributesbuilder_set_map(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_mode(a: number, b: number): void;
export function beatmapattributesbuilder_set_mods(a: number, b: number, c: number): void;
export function beatmapattributesbuilder_set_od(a: number, b: number, c: number): void;
export function difficulty_calculate(a: number, b: number): number;
export function difficulty_gradualDifficulty(a: number, b: number): number;
export function difficulty_gradualPerformance(a: number, b: number): number;
export function difficulty_new(a: number, b: number): void;
export function difficulty_set_fixed_ar(a: number, b: number): void;
export function difficulty_set_fixed_cs(a: number, b: number): void;
export function difficulty_set_fixed_hp(a: number, b: number): void;
export function difficulty_set_fixed_od(a: number, b: number): void;
export function difficulty_set_hardrock_offsets(a: number, b: number): void;
export function difficulty_set_lazer(a: number, b: number): void;
export function difficulty_set_mods(a: number, b: number, c: number): void;
export function difficulty_set_passed_objects(a: number, b: number, c: number): void;
export function difficulty_strains(a: number, b: number): number;
export function gradualdifficulty_collect(a: number, b: number): void;
export function gradualdifficulty_nRemaining(a: number): number;
export function gradualdifficulty_next(a: number): number;
export function gradualdifficulty_nth(a: number, b: number): number;
export function gradualperformance_next(a: number, b: number, c: number): void;
export function gradualperformance_nth(a: number, b: number, c: number, d: number): void;
export function performance_calculate(a: number, b: number, c: number): void;
export function performance_new(a: number, b: number): void;
export function performance_setHitresultGenerator(a: number, b: number, c: number): void;
export function performance_set_accuracy(a: number, b: number, c: number): void;
export function performance_set_combo(a: number, b: number, c: number): void;
export function performance_set_fixed_ar(a: number, b: number): void;
export function performance_set_fixed_cs(a: number, b: number): void;
export function performance_set_fixed_hp(a: number, b: number): void;
export function performance_set_fixed_od(a: number, b: number): void;
export function performance_set_hardrock_offsets(a: number, b: number): void;
export function performance_set_hitresult_priority(a: number, b: number): void;
export function performance_set_hp(a: number, b: number, c: number): void;
export function performance_set_large_ticks_hits(a: number, b: number, c: number): void;
export function performance_set_lazer(a: number, b: number): void;
export function performance_set_legacy_total_score(a: number, b: number, c: number): void;
export function performance_set_misses(a: number, b: number, c: number): void;
export function performance_set_mods(a: number, b: number, c: number): void;
export function performance_set_n100(a: number, b: number, c: number): void;
export function performance_set_n300(a: number, b: number, c: number): void;
export function performance_set_n50(a: number, b: number, c: number): void;
export function performance_set_n_geki(a: number, b: number, c: number): void;
export function performance_set_n_katu(a: number, b: number, c: number): void;
export function performance_set_od(a: number, b: number, c: number): void;
export function performance_set_passed_objects(a: number, b: number, c: number): void;
export function performance_set_slider_ends_hit(a: number, b: number, c: number): void;
export function performance_set_small_ticks_hits(a: number, b: number, c: number): void;
export function gradualdifficulty_new(a: number, b: number): number;
export function gradualperformance_new(a: number, b: number): number;
export function difficulty_set_ar(a: number, b: number, c: number): void;
export function difficulty_set_cs(a: number, b: number, c: number): void;
export function difficulty_set_hp(a: number, b: number, c: number): void;
export function difficulty_set_od(a: number, b: number, c: number): void;
export function performance_set_ar(a: number, b: number, c: number): void;
export function performance_set_cs(a: number, b: number, c: number): void;
export function gradualperformance_nRemaining(a: number): number;
export function __wbg_get_difficultyattributes_aim(a: number, b: number): void;
export function __wbg_get_difficultyattributes_aimDifficultSliderCount(a: number, b: number): void;
export function __wbg_get_difficultyattributes_aimTopWeightedSliderFactor(a: number, b: number): void;
export function __wbg_get_difficultyattributes_flashlight(a: number, b: number): void;
export function __wbg_get_difficultyattributes_sliderFactor(a: number, b: number): void;
export function __wbg_get_difficultyattributes_speed(a: number, b: number): void;
export function difficulty_set_clock_rate(a: number, b: number, c: number): void;
export function performance_set_clock_rate(a: number, b: number, c: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
export function __wbindgen_export_3(a: number): void;
